import { useState, useEffect } from 'react';
import { EPISODES } from '@/config/site';

export interface PodcastEpisode {
  id: string;
  title: string;
  audioUrl: string;
  description: string;
  pubDate: string;
  pubDateRaw: string;
  durationSeconds: number;
  image: string;
  link: string;
}

export interface PodcastFeedInfo {
  title: string;
  description: string;
  image: string;
  link: string;
}

interface FeedState {
  episodes: PodcastEpisode[];
  feedInfo: PodcastFeedInfo | null;
  isLoading: boolean;
  error: string | null;
}

/**
 * Where the episodes come from, in order:
 *
 * 1. /episodes.json — generated by scripts/fetch-episodes.mjs before every
 *    build and refreshed on a schedule. Same origin as the site, so it always
 *    loads: no CORS, no rate limit, no third party in the path.
 * 2. api.rss2json.com — tried afterwards only to catch an episode published
 *    since the last build. It is a free service that rate-limits and goes
 *    down, so it can only ever add freshness; a failure here is ignored and
 *    the visitor keeps the episodes from step 1.
 *
 * The page previously depended on step 2 alone, which is why it could show no
 * episodes at all.
 */
const FEED_URL = 'https://anchor.fm/s/3c8f8270/podcast/rss';
const STATIC_EPISODES_URL = `${import.meta.env.BASE_URL}episodes.json`;

interface Rss2JsonItem {
  guid?: string;
  link?: string;
  title?: string;
  description?: string;
  content?: string;
  pubDate?: string;
  thumbnail?: string;
  enclosure?: { link?: string; duration?: number | string; image?: string };
}

interface StaticEpisode {
  id: string;
  title: string;
  audioUrl: string;
  description: string;
  pubDateRaw: string;
  durationSeconds: number;
  image: string;
  link: string;
}

const stripHtml = (html: string) => html.replace(/<[^>]*>/g, '').trim();

// RSS descriptions often end with a run of social hashtags meant for other
// platforms (#TrasigMenHel #PersonligUtveckling ...). They're real content,
// but read as noise inside a webpage paragraph, so trim a trailing hashtag
// run for display rather than fabricating replacement copy.
const stripTrailingHashtags = (text: string) =>
  text.replace(/(\s*#[^\s#]+){2,}\s*$/u, '').trim();

/**
 * rss2json hands back dates as "2026-09-01 05:00:00" while raw RSS uses
 * "Mon, 01 Sep 2026 05:00:00 GMT". Safari refuses the first form, so
 * normalise it before parsing rather than trusting `new Date` with either.
 */
const toTimestamp = (value: string) => {
  if (!value) return NaN;
  const normalised = /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(value)
    ? value.replace(' ', 'T') + 'Z'
    : value;
  return new Date(normalised).getTime();
};

const formatDate = (value: string) => {
  const time = toTimestamp(value);
  if (Number.isNaN(time)) return '';
  return new Date(time).toLocaleDateString('sv-SE', { day: 'numeric', month: 'long', year: 'numeric' });
};

const byNewestFirst = (a: PodcastEpisode, b: PodcastEpisode) => {
  const at = toTimestamp(a.pubDateRaw);
  const bt = toTimestamp(b.pubDateRaw);
  if (Number.isNaN(at) && Number.isNaN(bt)) return 0;
  if (Number.isNaN(at)) return 1;
  if (Number.isNaN(bt)) return -1;
  return bt - at;
};

const matchesFeatured = (episode: PodcastEpisode, match: string | RegExp) =>
  match instanceof RegExp
    ? match.test(episode.title) || match.test(episode.id)
    : episode.title.toLowerCase().includes(match.toLowerCase()) || episode.id === match;

/**
 * Applies the site's own rules: drop the hidden titles, sort newest first,
 * then move a pinned episode to the front.
 *
 * The hidden-title filter deliberately gives up if it would empty the list.
 * Showing every episode, test upload included, beats a page that says the
 * podcast has none.
 */
const prepare = (episodes: PodcastEpisode[]): PodcastEpisode[] => {
  const visible = episodes.filter(
    (episode) => !EPISODES.hiddenTitlePatterns.some((pattern) => pattern.test(episode.title))
  );
  const result = (visible.length > 0 ? visible : episodes).slice().sort(byNewestFirst);

  if (EPISODES.featuredMatch) {
    const index = result.findIndex((episode) => matchesFeatured(episode, EPISODES.featuredMatch!));
    if (index > 0) result.unshift(...result.splice(index, 1));
  }
  return result;
};

const fromStatic = (episode: StaticEpisode): PodcastEpisode => ({
  id: episode.id,
  title: episode.title,
  audioUrl: episode.audioUrl,
  description: stripTrailingHashtags(episode.description || ''),
  pubDate: formatDate(episode.pubDateRaw),
  pubDateRaw: episode.pubDateRaw,
  durationSeconds: episode.durationSeconds || 0,
  image: episode.image || '',
  link: episode.link || '',
});

const fromRss2Json = (item: Rss2JsonItem, fallbackImage: string): PodcastEpisode => ({
  id: item.guid || item.link || '',
  title: stripHtml(item.title || ''),
  audioUrl: item.enclosure?.link || '',
  description: stripTrailingHashtags(stripHtml(item.description || item.content || '')),
  pubDate: formatDate(item.pubDate || ''),
  pubDateRaw: item.pubDate || '',
  durationSeconds: Number(item.enclosure?.duration) || 0,
  image: item.thumbnail || item.enclosure?.image || fallbackImage,
  link: item.link || '',
});

const formatDuration = (seconds: number) => {
  if (!seconds || Number.isNaN(seconds)) return '';
  return `${Math.floor(seconds / 60)} min`;
};

export const usePodcastFeed = () => {
  const [state, setState] = useState<FeedState>({
    episodes: [],
    feedInfo: null,
    isLoading: true,
    error: null,
  });

  useEffect(() => {
    let cancelled = false;

    const loadStatic = async () => {
      const response = await fetch(STATIC_EPISODES_URL, { cache: 'no-cache' });
      if (!response.ok) throw new Error(`episodes.json svarade ${response.status}`);
      const data = await response.json();
      if (!Array.isArray(data.episodes)) throw new Error('episodes.json kunde inte tolkas');

      const episodes = prepare((data.episodes as StaticEpisode[]).filter((e) => e.audioUrl).map(fromStatic));
      if (episodes.length === 0) throw new Error('episodes.json innehöll inga avsnitt');

      return {
        episodes,
        feedInfo: data.feed
          ? {
              title: data.feed.title || '',
              description: stripTrailingHashtags(data.feed.description || ''),
              image: data.feed.image || '',
              link: data.feed.link || '',
            }
          : null,
      };
    };

    const loadLive = async () => {
      const response = await fetch(
        'https://api.rss2json.com/v1/api.json?rss_url=' + encodeURIComponent(FEED_URL)
      );
      if (!response.ok) throw new Error('rss2json svarade ' + response.status);

      const data = await response.json();
      if (data.status !== 'ok' || !Array.isArray(data.items)) throw new Error('rss2json kunde inte tolkas');

      const episodes = prepare(
        (data.items as Rss2JsonItem[])
          .map((item) => fromRss2Json(item, data.feed?.image || ''))
          .filter((episode) => episode.id && episode.audioUrl)
      );
      if (episodes.length === 0) throw new Error('rss2json innehöll inga avsnitt');

      return {
        episodes,
        feedInfo: data.feed
          ? {
              title: stripHtml(data.feed.title || ''),
              description: stripTrailingHashtags(stripHtml(data.feed.description || '')),
              image: data.feed.image || '',
              link: data.feed.link || '',
            }
          : null,
      };
    };

    const run = async () => {
      let haveEpisodes = false;

      try {
        const result = await loadStatic();
        haveEpisodes = true;
        if (!cancelled) setState({ ...result, isLoading: false, error: null });
      } catch (error) {
        console.warn('Kunde inte läsa episodes.json:', error);
      }

      // Freshness pass. Only replaces what is already shown if it actually
      // carries something newer, and never turns a working page into an error.
      try {
        const live = await loadLive();
        if (cancelled) return;

        setState((current) => {
          const newestShown = current.episodes[0] ? toTimestamp(current.episodes[0].pubDateRaw) : NaN;
          const newestLive = toTimestamp(live.episodes[0].pubDateRaw);
          const isNewer =
            !Number.isFinite(newestShown) ||
            (Number.isFinite(newestLive) && newestLive > newestShown) ||
            live.episodes.length > current.episodes.length;

          if (!isNewer && current.episodes.length > 0) return current;
          return { ...live, isLoading: false, error: null };
        });
      } catch (error) {
        if (!haveEpisodes && !cancelled) {
          setState({
            episodes: [],
            feedInfo: null,
            isLoading: false,
            error: error instanceof Error ? error.message : 'Ett fel uppstod',
          });
        }
      }
    };

    run();
    return () => {
      cancelled = true;
    };
  }, []);

  return state;
};

export { formatDuration };
